### PR TITLE
Add advanced capabilities

### LINKED ISSUE #1653: Feature Request: Restrict Menu Options by role
I would like to hide some of the sub menu options based on user role. I want some users to be able to add redirects and view the 404s and logs but not able to make new groups or configure the options.

"Redirects | Groups | Log | 404s | Import/Export | Options | Support"

### LINKED ISSUE #2040: Adding class names or hooks into react code
The is much more of a feature request than a bug. The plugin itself is great. 

### Summary

We're hoping to use it on a multisite installation for a number of clients and would love to simplify the user experience for them. There is a ton of neat functionality in the plugin, but we'd love to avoid confusing our clients with the extra features. Here is how the interface looks normally:

redirection-full-functionality

And here is what we're trying to accomplish:

redirection-simplified-functionality

We've been able to accomplish this using the following CSS:

```css
.redirection .subsubsub-container,
.redirection .redirect-table-display__filter,
.redirection select[name="group"],
.redirection .redirect-multioption,
.redirection .redirection-edit_advanced,
.redirection table.edit-redirection tr:nth-child(2),
.redirection table.edit-redirection tr:nth-child(4),
.redirection .redirect-searchbox .redirect-dropdownbutton li:nth-child(3),
.redirection-poweredby {
	display: none;
}
```

We obviously don't love this approach since the selectors are so vague and can easily cause problems when the plugin is updated. Specifically, we're worried about the `nth-child()` selectors.

Is there any chance you'd be open to adding class names in your react code to many of these elements so they're easier to target? If that's not possible, could you provide hooks through JavaScript or PHP to allow us to remove the elements there?

Thanks a ton.

### PR DESCRIPTION
**Pull request by johngodley**
Add more advanced capabilities that restrict access to different parts of the plugin, which can then be extended using hooks to provide a more customised environment. For example, you can give editors permission to create redirects but not modify options or delete anything.

Fixes #2040
Fixes #1653

### CODE REVIEW

**Comment by jg314** [comment]
Wow, this is very exciting! We're pumped for this to be merged into the plugin.

**Comment by johngodley** [comment]
@jg314 this is in 4.6 beta 1, if you want to give it a try. Let me know how it goes.

https://github.com/johngodley/redirection/releases/tag/4.6-beta-1

**Comment by jg314** [comment]
This is great. Is there an easy way for us to see what we can customize? If not, we can always look through the files. But with 61 files changing, it might be tough to find all the new functionality you added. Thanks a ton for building this. I'm excited to look it over.

**Comment by johngodley** [comment]
Sorry, should have added that info: https://redirection.me/developer/permissions/

**Comment by jg314** [comment]
Great, thanks @johngodley. I'm hopeful our team should be able to look this over in the coming week, but we'll see how it shakes out.

**Comment by jg314** [comment]
@johngodley, we unfortunately weren't able to get to this during the week, but I'm crossing my fingers for next week. Thanks for being patient with us.

**Comment by jg314** [comment]
@johngodley, we were able to take some time to look this over. Most importantly, thank you for all the work you put into this. This functionality will not only be helpful for us, but anyone who's looking to provide limited access to redirects for specific roles.

Overall, our testing went incredibly well. We used the following code to limit basic administrators (not super admins) on a multisite install so they can only create, delete and modify existing redirects:

```php
/**
 * Simplify the Redirection functionality available for clients.
 *
 * @see https://redirection.me/developer/permissions/
 * @param string $capability The original capability required to use the functionality.
 * @param string $permission The specific Redirection functionality requested.
 * @return string The existing capability or an updated one.
 */
function wi_set_redirection_capabilities( $capability, $permission ) {

	$only_super_admin_perms = array(
		'redirection_cap_group_manage',
		'redirection_cap_group_add',
		'redirection_cap_group_delete',
		'redirection_cap_log_manage',
		'redirection_cap_log_delete',
		'redirection_cap_404_manage',
		'redirection_cap_404_delete',
		'redirection_cap_io_manage',
		'redirection_cap_option_manage',
		'redirection_cap_support_manage',
		'redirection_cap_site_manage',
	);

	if ( in_array( $permission, $only_super_admin_perms, true ) ) {
		return 'manage_network';
	}

	return $capability;
}
add_filter( 'redirection_capability_check', 'wi_set_redirection_capabilities', 10, 2 );
```

We were also able to make our CSS to simplify the experience of working with redirects more specific, making it more future proof:

```php
/**
 * Simplify the Redirection interface for clients.
 */
function wi_simplify_redirection_interface() {

	$current_screen = get_current_screen();
	if ( $current_screen->id !== 'tools_page_redirection' || current_user_can( 'manage_network' ) ) {
		return false;
	}

	?>
	<style>

		.redirection .redirect-table-display__filter,
		.redirection select[name="group"],
		.redirection .redirect-multioption,
		.redirection .redirection-edit_advanced,
		.redirection table .redirect-edit__sourcequery,
		.redirection table .redirect-edit__group,
		.redirection .redirect-searchbox .redirect-dropdownbutton li:nth-child(3),
		.redirection-poweredby {
			display: none;
		}

		.redirection .edit-redirection .edit-redirection_warning a:hover,
		.redirection .edit-redirection .edit-redirection_warning a:focus {
			cursor: default;
			text-decoration: none;
			box-shadow: none;
		}

	</style>
	<?php
}
add_action( 'admin_head', 'wi_simplify_redirection_interface' );
```

We noticed a few minor issues and had one request:

1. The mention on https://redirection.me/developer/permissions/ of using `add_filter( 'redirection_capability_check'...` seems to leave out the priority and the number of arguments. Since two arguments are passed, it's required in the `add_filter()` call to avoid an error.
2. Restricting the permissions worked very well, but when trying to search for a page within the Target URL we get a console error that says `message: "Sorry, you are not allowed to do that.", code: "rest_forbidden"`. Otherwise, basic administrators were able to create, edit and delete redirects as needed.
3. This is definitely more of a request, but in our CSS we are still including a selector for `.redirection .redirect-searchbox .redirect-dropdownbutton li:nth-child(3)` to remove the "Search title" option in the dropdown. It would be great if there was a more specific selector to make it more future proof.
4. You're likely not finished with the documentation, but I was a little confused on https://redirection.me/developer/permissions/ by the text about the `redirection_capability` filter and the `redirection_capability()` function. It doesn't look like those exist, but I might be missing it somewhere.

I think that's it. Obviously, take or leave any of my suggestions. Thanks again for everything. I'm excited for you to roll out these features.

**Comment by jg314** [comment]
@johngodley, I wanted to follow up to see if you had a chance to look over these notes. Is there anything I can clarify here?

**Comment by johngodley** [comment]
4.6 was released with the above included.

**Comment by jg314** [comment]
Great to hear @johngodley! Thanks again for all the work here. We're really excited about these changes.

**Pull request merged**
