### PR TITLE
Added composer support

### PR DESCRIPTION
**Pull request by spacedmonkey**
Added the composer.json file, to make this github repo compatible with composer. All that needs to done to support is merge this file.

### CODE REVIEW

**Comment by johngodley** [comment]
Hi, can you split the composer change from the other changes? I'll merge it in when split

**Comment by johngodley** [comment]
Also, can you remove the Time specific changes?

**Comment by strarsis** [comment]
New PR derived from recent master: https://github.com/johngodley/redirection/pull/664

**Comment by johngodley** [comment]
Closing this in favour of #664

**Pull request closed without merging**
