### PR TITLE
Multi site

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Small edits to relocate existing code to method to be run per-site.
Original method replaced with branching logic based upon internal WordPress function `is_multisite()`

If the site is multisite, we get all sites using WordPress internal function `wp_get_sites()`, iterate over them, switch blog to each one, run the function (which will get the option for db version per-site, and continue existing logic to install or upgrade), and then restore the blog.

If the site is not multisite, we incur one additional function call to the relocated method using 100% same code as previously used.

As unit-tests seem not to be working (the test-suite itself has errors in all versions of PHP, likely due to major version upgrade), I will manually test as soon as I have time

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
Just re-ran tests it works for latest, just not 4.4. https://travis-ci.org/Lewiscowles1986/redirection. Would be really nice to know at which point 4.4 won't be needed

**Comment by johngodley** [comment]
Thanks for this work!

I'm not overly familiar with multisite so forgive these questions if they're not appropriate.

Is it possible the plugin might not be installed on every subsite? If yes we'll need to check that it's installed first before upgrading.

Also, the upgrade function runs on every Redirection page load. On a large multisite this could be quite an overhead.  I think we'll need to make use of something like `get_site_option` to get the 'master' Redirection version and only run the subsite upgrades if that changes. This way we only have one version check.

I'll get a multisite installation setup and try this out.

**Comment by johngodley** [comment]
By the way, if you rebase on master the unit tests failures should disappear

**Comment by Lewiscowles1986** [comment]
Right there is a little more work on this then. 

 * We can get the list of plugins installed on a per-site basis (tbh never really thought installing tables would hurt which is all this is for)

 * Could we tie this into a plugin activation hook and new site hook (I thought it was just when the plugin is activated right now) which is only called on install?

 * Happy to work on this as I really appreciate the plugin being open-source

**Comment by johngodley** [comment]
Just to add that I adapted the code here and added multi-site code in version 2.10 along with some other multi-site cases. Thanks for the work!

**Comment by plethoradesign** [comment]
I'm running WordPress 5.3.2 and Redirection 4.6.2 on a multisite network, and have tried removing the plugin and reinstalling it, but no site-specific DB tables are created, nor does saving the settings on /wp-admin/tools.php?page=redirection.php make any difference.

What is the status of this plugin on multisite? It looks to me like it still doesn't work on multisite.

**Comment by johngodley** [comment]
@plethoradesign please can you create a separate issue rather than add to an old and closed one?

**Comment by plethoradesign** [comment]
will do

**Pull request closed without merging**
