### PR TITLE
Dashboard widget

### LINKED ISSUE #194: Feature Request: Dashboard Widget showing top 404s and Redirects
It would be really handy to have a dashboard widget that shows the top 404s so that you can see at a glance if something is wrong, or pick the next URL to create a redirect for.

Similarly it would be nice to be able to see at a glance which redirects are being hit the most.

### PR DESCRIPTION
**Pull request by ianmjones**
Resolves #194 

This PR adds a dashboard widget that shows the top 404s and redirects.

redirection dashboard widget

Each section has a "View All" link or quickly getting to the appropriate place in the main settings page.

By default the lists show the top 5, but `REDIRECTION_WIDGET_TOP` can be defined to change the count:

`define('REDIRECTION_WIDGET_TOP', 10);`

### CODE REVIEW

**Comment by Beee4life** [comment]
I like this feature... +1

**Comment by ianmjones** [comment]
@johngodley I've merged in `master` and now use "Hits" instead of "Count" in the widget to fit in better with what Redirection uses elsewhere.

**Comment by johngodley** [comment]
Thanks @ianmjones!

The grouping by 404 SQL is inefficient and could cause some problems if it's shown on the main dashboard of a blog with a lot of 404s.

Note the inefficiency is caused by the design of the table and not the query itself - the table doesn't support efficient grouping like that.

There are a lot of feature requests to group 404s, and when it is implemented the query will be efficient.

If it's ok with you I'll leave this PR open, pending DB changes. In the meantime you may want to implement it as a standalone plugin so it's not tied directly to Redirection.

**Comment by ianmjones** [comment]
No worries @johngodley, totally understand about the grouping.

I'm a big proponent of indexes being unique, it helps most DB engines a huge amount. For example, the index for `url` could be changed to be a composite unique index on `url` and `id`.

That's probably not quite what you're envisioning, I suspect you're needing to break up and shorten the `url` for more efficient grouping, but I thought it might be of interest anyway!

I'll sit tight until you let me know you've made the changes you need for 404 grouping and then I'll fix up this PR.

**Comment by ianmjones** [comment]
Never heard back and I no longer have time to work on this anyway, closing.

**Pull request closed without merging**
