### PR TITLE
Trailing Slashes

### PR DESCRIPTION
**Pull request by tomcat90**
This just adds two things. The first is it adds to the SQL query to look for both the URI with a trailing slash and without it. The second thing is that it does a check for rtrim($this->url, "/") === rtrim($url, "/") instead of just doing the rtrim on the $url. This allows it to match on both /foo and /foo/.

### CODE REVIEW

**Comment by Zyniker13** [comment]
Arguably, doesn't this *reduce* the functionality of the plugin? For those who want matching both with and without the trailing slash, the plugin already supports this with a bit of simple regex (e.g., \/foo\/? will match both /foo and /foo/). If these changes are merged, then those who do *not* want the trailing slash to be 'ignored' will lose functionality.

Alternatively, this could be added as an option in the plugin, which seems the better course.

**Comment by tomcat90** [comment]
I guess yes if someone wanted to do separate redirects based on slash this would remove that ability. Although I don't understand how that would be a needed use case as most browsers treat /foo the same as /foo/

**Comment by Zyniker13** [comment]
I agree that it would probably be a limited subset of users who would ever even *consider* making /foo and /foo/ redirect differently, but it does seem that the best practice is *not* to remove features just because they seem little used (especially if retaining them doesn't cost anything). Personally, I routinely take the regex approach (i.e., ending with `\/?$`), precisely because I want to avoid the potential trailing slash issue.

I would say move this into Options and just have a checkbox for "ignore trailing slash" or similar.

**Comment by YesThatAllen** [comment]
In a perfect world, I'd love an option next to `regex` which is `match trailing slash` and on by default.

When entering `/foo` it would match `/foo` and `/foo/` but not `/foo/bar`

As it stands, I have to manually create all redirections as regex and add `[/]*$` to the end of `/foo`. It's working, but is a pain

**Comment by Zyniker13** [comment]
Agreed. A per-redirect option would be better than a simple on/off toggle in Options. However, I would add that a per-redirect option coupled with a default toggle in Options would be even better.

It would definitely simplify things. I've been adding `\/?$` at the end of all of my redirects.

**Comment by Sophist-UK** [comment]
Better for non regex to remove trailing slashes and if someone wants different redirects with / without trailing slash they can use regex to create this. i.e.

`^/something$` and `^/something/$`

See also my partial solution in #171 which has a better replacement for line 302.

**Comment by johngodley** [comment]
Thanks for the code. I have been working towards implementing this as part of other improvements, and it will be added in #1377

This is marked as alpha. If you are interesting in testing it then you can find a download at https://github.com/johngodley/redirection/releases/tag/4.0-alpha-1

I would appreciate any feedback, either here on Github, or directly at https://redirection.me/contact/

I'll close this as 'done'.

**Pull request closed without merging**
