### PR TITLE
add email notifications for 404s

### PR DESCRIPTION
**Pull request by ghost**
Send notifications on daily, weekly, or monthly basis.  

I had client request this feature, thought others might find it useful.

### CODE REVIEW

**Comment by ydlr** [comment]
I just noticed issue #130. Probably should have checked before sending pull request. I'll close in a few days if there's no comment.

**Comment by johngodley** [comment]
Sorry, I've been meaning to look at this. It looks like a good and well thought out feature. I'll get back to you once the 2.7 branch has stablised

**Comment by brendanmullan** [comment]
Is this being added to the core plugin at some point?

**Comment by fharper** [comment]
Any news on that? The PR is still open even with the comment on the issue #130. I would love to have this PR merged.

**Comment by fharper** [comment]
For folks following this PR, it wasn't merged. See @johngodley comment at https://github.com/johngodley/redirection/issues/130#issuecomment-268987122

> Most sites I know receive too many 404s to realistically send in an email. The plugin provides an RSS feed so you can add these into an RSS reader.
> 
> I'm going to close this as I dont think the plugin should get involved in emails.

But there isn't any RSS for 404 yet, I made a feature request a couple of years ago https://github.com/johngodley/redirection/issues/1667

**Pull request closed without merging**
