### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by mugurcagdas**
Hello,
I translated this plugin language file from EN to TUR.
Could you please check it and merge?
Proofread, there is no fault, double checked.
Kindly waiting for your answer.
Thanks in advance.
Best Regards,
mugurcagdas

### CODE REVIEW

**Comment by johngodley** [comment]
Can you upload the translation through https://translate.wordpress.org/projects/wp-plugins/redirection ? That's where they come from

**Comment by mugurcagdas** [comment]
I am not sure how to upload my translation to this link. I already translated language file with Poedit.

**Comment by johngodley** [comment]
That's great, and thanks for doing that. However, I'm afraid I can't accept the files here. You will need to import the file to translate.wordpress.org. If there are any Turkish translators they will also be able to validate the translations.

Once the translations are on translate.wordpress.org and have been approved, the plugin will automatically download the files, and they will then be available.

I know this is extra work, but that's how plugin translations work now.

**Comment by mugurcagdas** [comment]
Ok, thanks for reply. You are right. I just want to everyone sees my effort :/
I will try to translate it via translate.wordpress.org

**Comment by johngodley** [comment]
Thanks! I know you can import the file so hopefully it should be straightforward. I'll close this PR

**Pull request closed without merging**
